# Generated by Django 3.1.13 on 2021-11-20 12:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_auto_20211120_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiya')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=100, verbose_name='Tuman/Shahar')),
                ('street', models.CharField(max_length=55, verbose_name="Ko'cha")),
                ('house', models.CharField(max_length=255, verbose_name='Massiv, Daha, Kvarta, uy nomeri')),
                ('postcode', models.PositiveIntegerField(blank=True, verbose_name='Pochta indexi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-pochta')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon')),
                ('message', models.TextField(blank=True, verbose_name="Qo'shimcha xabar")),
                ('payment', models.CharField(blank=True, max_length=55, verbose_name="To'lov turi")),
                ('shipping', models.CharField(blank=True, max_length=55, verbose_name='Yetkazib berish')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Buyurtma egasi')),
            ],
            options={
                'verbose_name': 'buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='narx')),
                ('quantity', models.PositiveIntegerField(default='1', validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Soni')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='buyurtma')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'buyurtma',
            },
        ),
    ]
