# Generated by Django 3.1.13 on 2021-11-26 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
    ]
