# Generated by Django 3.1.13 on 2022-01-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211126_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pochta indexi'),
        ),
    ]
