# Generated by Django 3.1.13 on 2021-11-28 00:51

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='slug')),
                ('body', models.TextField(blank=True, verbose_name='Tavsifi')),
                ('image', models.ImageField(blank=True, default='default.apng', null=True, upload_to='', verbose_name='rasm')),
                ('news', models.BooleanField(default=False, verbose_name='Yangilik')),
                ('stock', models.BooleanField(default=False, verbose_name='Chegirma')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='slug')),
                ('icon', models.ImageField(upload_to='', verbose_name='Hamkor logosi')),
                ('site_url', models.URLField(max_length=255, verbose_name='Websayt urli')),
            ],
            options={
                'verbose_name_plural': 'Partners',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Savollar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('question', models.CharField(max_length=512, verbose_name='Savol')),
                ('answer', models.CharField(max_length=512, verbose_name='Javob')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ('order',),
            },
        ),
    ]
