# Generated by Django 3.1.13 on 2021-11-28 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('-created',), 'verbose_name': 'hamkor', 'verbose_name_plural': 'Hamkorlar'},
        ),
    ]
