# Generated by Django 3.1.13 on 2022-01-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211128_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='new',
            name='body_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='new',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='new',
            name='title_uz',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_uz',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='savollar',
            name='answer_ru',
            field=models.CharField(max_length=512, null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='savollar',
            name='answer_uz',
            field=models.CharField(max_length=512, null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='savollar',
            name='question_ru',
            field=models.CharField(max_length=512, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='savollar',
            name='question_uz',
            field=models.CharField(max_length=512, null=True, verbose_name='Savol'),
        ),
    ]
