# Generated by Django 3.1.13 on 2022-01-04 14:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_auto_20211212_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Baho')),
                ('person', models.CharField(blank=True, max_length=55, verbose_name='Xaridor')),
                ('contact', models.CharField(blank=True, max_length=13, verbose_name='Kontakti')),
                ('comment', models.TextField(blank=True, verbose_name='Fikr')),
                ('published', models.BooleanField(default=False, verbose_name='Nashr qilindi')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name="qo'shildi")),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'reyting',
                'verbose_name_plural': 'Reyting',
            },
        ),
    ]
