# Generated by Django 3.1.13 on 2022-01-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Yangilandi')),
                ('currency', models.DecimalField(blank=True, decimal_places=2, max_digits=100, verbose_name='USD Reytingi')),
            ],
            options={
                'verbose_name': 'kurs',
                'verbose_name_plural': 'Dollar kursi',
                'ordering': ('-updated',),
            },
        ),
    ]
