# Generated by Django 3.1.13 on 2022-01-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, verbose_name='USD Reytingi'),
        ),
    ]
