# Generated by Django 3.1.13 on 2021-11-25 20:45

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('first_large_image', models.ImageField(blank=True, upload_to='', verbose_name='Birinchi HD rasm')),
                ('show_features', models.BooleanField(default=True, verbose_name="Xizlat turlari haqida malumotni ko'rsatish")),
                ('first_feature', models.TextField(max_length=512, verbose_name='Birinchi xizmat turi')),
                ('second_feature', models.TextField(max_length=512, verbose_name='Uchinchi xizmat turi')),
                ('third_feature', models.TextField(max_length=512, verbose_name='Ikkinchi xizmat turi')),
                ('feature_image', models.ImageField(blank=True, upload_to='', verbose_name='Xizmat turlariga oid rasm')),
                ('show_statistics', models.BooleanField(default=True, verbose_name="Statistika bo'limini ko'rsatish")),
                ('products_in_sale', models.IntegerField(blank=True, default=0, verbose_name='Sotuvdagi productlar')),
                ('products_in_sale_description', models.CharField(blank=True, max_length=155, verbose_name='Sotuvdagi mahsulotlar tavsifi')),
                ('community_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name="Jamoa jamg'armasi")),
                ('community_earnings_description', models.CharField(blank=True, max_length=155, verbose_name='Qisqacha tavsif')),
                ('buyer_count', models.IntegerField(blank=True, default=0, verbose_name='Xaridorlar soni')),
                ('buyer_count_description', models.CharField(blank=True, max_length=155, verbose_name='Xaridorlar haqida qisqacha tavsif')),
                ('show_think_about_customers', models.BooleanField(default=True, verbose_name="Xaridorlar haqida qaygurish bo'limini ko'rsatish")),
                ('think_about_customers_image', models.ImageField(blank=True, upload_to='', verbose_name="Xaridorlar haqida o'ylaymiz rasmi")),
                ('think_about_customers_description', models.TextField(blank=True, max_length=512, verbose_name='Qisqacha tavsif')),
            ],
            options={
                'verbose_name': 'malumot',
                'verbose_name_plural': 'Kompaniya haqida',
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Yutuq nomi')),
                ('image', models.ImageField(upload_to='', verbose_name='Yutuq rasmi')),
            ],
            options={
                'verbose_name': 'yutuq',
                'verbose_name_plural': 'Yutuqlar',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Aloqa sarlavhasi')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Qisqacha tavsif')),
                ('email', models.EmailField(max_length=254, verbose_name='E.pochta')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon raqam')),
                ('adress', models.CharField(max_length=155, verbose_name='Manzil')),
                ('fax', models.CharField(blank=True, max_length=15, verbose_name='Fax raqami')),
            ],
            options={
                'verbose_name': 'malumot',
                'verbose_name_plural': 'Kontaktlar',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=155, verbose_name='Xususiyat nomi')),
                ('description', models.TextField(max_length=155, verbose_name='Qisqacha tavsif')),
                ('icon_class', models.CharField(max_length=55, verbose_name='Ikonka nomi')),
            ],
            options={
                'verbose_name': 'xususiyat',
                'verbose_name_plural': 'Xususiyatlar',
            },
        ),
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=155, verbose_name='Xodimning ismi sharfi')),
                ('role', models.CharField(max_length=155, verbose_name='Lavozimi')),
                ('facebook', models.CharField(blank=True, max_length=55, verbose_name='Facebookdagi foydalanuvchi nomi')),
                ('twitter', models.CharField(blank=True, max_length=55, verbose_name='Twitterdagi foydalanuvchi nomi')),
                ('instagram', models.CharField(blank=True, max_length=55, verbose_name='Instagram foydalanuvchi nomi')),
                ('telegram', models.CharField(blank=True, max_length=55, verbose_name='Telegram foydalanuvchi nomi')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Xodim rasmi')),
            ],
            options={
                'verbose_name': 'xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
    ]
