# Generated by Django 3.1.13 on 2021-11-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='first_feature',
            field=models.TextField(help_text="Xaridorlarga xizmat ko'rsatish haqida", max_length=512, verbose_name='Birinchi xizmat turi'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='second_feature',
            field=models.TextField(help_text="Onlayn qo'llab quvvatlash haqida", max_length=512, verbose_name='Uchinchi xizmat turi'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='third_feature',
            field=models.TextField(help_text="Xarid bo'yicha konsultatsiya haqida", max_length=512, verbose_name='Ikkinchi xizmat turi'),
        ),
    ]
