# Generated by Django 3.1.13 on 2021-11-28 01:12

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20211128_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon raqam')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'xabar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
    ]
