# Generated by Django 3.1.13 on 2022-01-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='buyer_count_description_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Xaridorlar haqida qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='buyer_count_description_uz',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Xaridorlar haqida qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='community_earnings_description_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='community_earnings_description_uz',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='first_feature_ru',
            field=models.TextField(help_text="Xaridorlarga xizmat ko'rsatish haqida", max_length=512, null=True, verbose_name='Birinchi xizmat turi'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='first_feature_uz',
            field=models.TextField(help_text="Xaridorlarga xizmat ko'rsatish haqida", max_length=512, null=True, verbose_name='Birinchi xizmat turi'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='products_in_sale_description_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Sotuvdagi mahsulotlar tavsifi'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='products_in_sale_description_uz',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Sotuvdagi mahsulotlar tavsifi'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='second_feature_ru',
            field=models.TextField(help_text="Onlayn qo'llab quvvatlash haqida", max_length=512, null=True, verbose_name='Uchinchi xizmat turi'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='second_feature_uz',
            field=models.TextField(help_text="Onlayn qo'llab quvvatlash haqida", max_length=512, null=True, verbose_name='Uchinchi xizmat turi'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='think_about_customers_description_ru',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='think_about_customers_description_uz',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='third_feature_ru',
            field=models.TextField(help_text="Xarid bo'yicha konsultatsiya haqida", max_length=512, null=True, verbose_name='Ikkinchi xizmat turi'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='third_feature_uz',
            field=models.TextField(help_text="Xarid bo'yicha konsultatsiya haqida", max_length=512, null=True, verbose_name='Ikkinchi xizmat turi'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='awards',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Yutuq nomi'),
        ),
        migrations.AddField(
            model_name='awards',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Yutuq nomi'),
        ),
        migrations.AddField(
            model_name='contact',
            name='adress_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='contact',
            name='adress_uz',
            field=models.CharField(max_length=155, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='contact',
            name='description_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='contact',
            name='description_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aloqa sarlavhasi'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aloqa sarlavhasi'),
        ),
        migrations.AddField(
            model_name='features',
            name='description_ru',
            field=models.TextField(max_length=155, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='features',
            name='description_uz',
            field=models.TextField(max_length=155, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='features',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Xususiyat nomi'),
        ),
        migrations.AddField(
            model_name='features',
            name='title_uz',
            field=models.CharField(max_length=155, null=True, verbose_name='Xususiyat nomi'),
        ),
        migrations.AddField(
            model_name='leaders',
            name='name_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Xodimning ismi sharfi'),
        ),
        migrations.AddField(
            model_name='leaders',
            name='name_uz',
            field=models.CharField(max_length=155, null=True, verbose_name='Xodimning ismi sharfi'),
        ),
        migrations.AddField(
            model_name='leaders',
            name='role_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='leaders',
            name='role_uz',
            field=models.CharField(max_length=155, null=True, verbose_name='Lavozimi'),
        ),
    ]
