# Generated by Django 3.1.13 on 2021-11-01 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Birth date'),
        ),
    ]
