# Generated by Django 3.1.13 on 2021-11-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211106_1201'),
        ('users', '0002_auto_20211101_0604'),
    ]

    operations = [
    ]
