# Generated by Django 3.1.13 on 2021-11-20 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211109_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Davlat')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Shahar')),
                ('postcode', models.PositiveIntegerField(blank=True, max_length=10, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Birth date')),
                ('gender', models.CharField(choices=[(1, 'Hidden'), (2, 'Male'), (3, 'Female')], default=1, max_length=55, verbose_name='Gender')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Foydalanuvchilar Profillari',
            },
        ),
    ]
