# Generated by Django 3.1.13 on 2021-11-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211120_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tuman/Shahar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='house',
            field=models.CharField(blank=True, max_length=255, verbose_name='Massiv, Daha, Kvarta, uy nomeri'),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Viloyat'),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, max_length=55, verbose_name="Ko'cha"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.PositiveIntegerField(blank=True, verbose_name='Manzil'),
        ),
    ]
