# Generated by Django 3.1.13 on 2021-11-20 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211120_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Foydalanuvchilar Profillari'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(1, 'Hidden'), (2, 'Male'), (3, 'Female')], default=1, max_length=55, verbose_name='Jins'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
    ]
