# Generated by Django 3.1.13 on 2021-12-04 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_auto_20211128_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalfPageAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(max_length=55, verbose_name='Reklama turi')),
                ('ad_title', models.CharField(max_length=55, verbose_name='Sarlavha')),
                ('ad_info', models.CharField(max_length=55, verbose_name='Qisqa tavsif')),
                ('button_link', models.URLField(max_length=255, verbose_name='Reklama hovolasi')),
                ('banner', models.ImageField(help_text='razmer: 610x200', upload_to='banners', verbose_name='Reklama banneri')),
            ],
            options={
                'verbose_name': 'malumot',
                'verbose_name_plural': 'Sahifa yarmini oluvchi reklama banneri',
            },
        ),
        migrations.CreateModel(
            name='HorizontalAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_discount', models.CharField(max_length=10, verbose_name='Chegirma miqdori (%)')),
                ('ad_title', models.CharField(max_length=55, verbose_name='Sarlavha')),
                ('ad_info', models.CharField(max_length=55, verbose_name='Qisqa tavsif')),
                ('button_link', models.URLField(max_length=255, verbose_name='Reklama havolasi')),
                ('banner', models.ImageField(help_text='razmer: 1240x198', upload_to='banners', verbose_name='Reklama banneri')),
            ],
            options={
                'verbose_name': 'malumot',
                'verbose_name_plural': 'Gorizontal uzun reklama banneri',
            },
        ),
        migrations.CreateModel(
            name='SidebarAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(max_length=55, verbose_name='Reklama turi')),
                ('ad_title', models.CharField(max_length=55, verbose_name='Sarlavha')),
                ('ad_info', models.CharField(max_length=55, verbose_name='Qisqa tavsif')),
                ('button_link', models.URLField(max_length=255, verbose_name='Reklama hovolasi')),
                ('banner', models.ImageField(help_text='razmer: 266x220', upload_to='banners', verbose_name='Reklama banneri')),
            ],
            options={
                'verbose_name': 'malumot',
                'verbose_name_plural': "Mahsulotlar bo'limida o'ng yondagi kichik reklama banneri",
            },
        ),
        migrations.CreateModel(
            name='TopProductsAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(max_length=55, verbose_name='Reklama turi')),
                ('ad_title', models.CharField(max_length=55, verbose_name='Sarlavha')),
                ('ad_info', models.CharField(max_length=55, verbose_name='Qisqa tavsif')),
                ('button_link', models.URLField(max_length=255, verbose_name='Reklama hovolasi')),
                ('banner', models.ImageField(help_text='razmer: 395x675', upload_to='banners', verbose_name='Reklama banneri')),
            ],
            options={
                'verbose_name': 'malumot',
                'verbose_name_plural': "Mahsus malumotlari bo'limi [chapdagi uzun vertikal reklama]",
            },
        ),
        migrations.CreateModel(
            name='HomePageBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(max_length=155, verbose_name='Banner turi')),
                ('banner_cat_text', models.CharField(blank=True, max_length=155, verbose_name='Banner Kategoriyasi')),
                ('banner_info', models.CharField(blank=True, max_length=255, verbose_name='Qisqacha tavsif')),
                ('button_link', models.URLField(blank=True, max_length=255, verbose_name='Banner tugmasi uchun havola')),
                ('banner_image', models.ImageField(help_text='rezmer: 1903x520', upload_to='banners', verbose_name='Banner katta rasmi')),
                ('banner_image_small', models.ImageField(help_text='rezmer: 70x70', upload_to='banners', verbose_name='Banner kichik rasmi')),
                ('banner_cat_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'Bosh sahifa bannerlari',
            },
        ),
    ]
