# Generated by Django 3.1.13 on 2022-01-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='halfpageadvert',
            name='ad_info_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='halfpageadvert',
            name='ad_info_uz',
            field=models.CharField(max_length=55, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='halfpageadvert',
            name='ad_title_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='halfpageadvert',
            name='ad_title_uz',
            field=models.CharField(max_length=55, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='halfpageadvert',
            name='ad_type_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Reklama turi'),
        ),
        migrations.AddField(
            model_name='halfpageadvert',
            name='ad_type_uz',
            field=models.CharField(max_length=55, null=True, verbose_name='Reklama turi'),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='banner_cat_text_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Banner Kategoriyasi'),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='banner_cat_text_uz',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Banner Kategoriyasi'),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='banner_info_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='banner_info_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='banner_type_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='Banner turi'),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='banner_type_uz',
            field=models.CharField(max_length=155, null=True, verbose_name='Banner turi'),
        ),
        migrations.AddField(
            model_name='horizontaladvert',
            name='ad_info_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='horizontaladvert',
            name='ad_info_uz',
            field=models.CharField(max_length=55, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='horizontaladvert',
            name='ad_title_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='horizontaladvert',
            name='ad_title_uz',
            field=models.CharField(max_length=55, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='sidebaradvert',
            name='ad_info_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='sidebaradvert',
            name='ad_info_uz',
            field=models.CharField(max_length=55, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='sidebaradvert',
            name='ad_title_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='sidebaradvert',
            name='ad_title_uz',
            field=models.CharField(max_length=55, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='sidebaradvert',
            name='ad_type_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Reklama turi'),
        ),
        migrations.AddField(
            model_name='sidebaradvert',
            name='ad_type_uz',
            field=models.CharField(max_length=55, null=True, verbose_name='Reklama turi'),
        ),
        migrations.AddField(
            model_name='topproductsadvert',
            name='ad_info_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='topproductsadvert',
            name='ad_info_uz',
            field=models.CharField(max_length=55, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='topproductsadvert',
            name='ad_title_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='topproductsadvert',
            name='ad_title_uz',
            field=models.CharField(max_length=55, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='topproductsadvert',
            name='ad_type_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Reklama turi'),
        ),
        migrations.AddField(
            model_name='topproductsadvert',
            name='ad_type_uz',
            field=models.CharField(max_length=55, null=True, verbose_name='Reklama turi'),
        ),
    ]
