# Generated by Django 3.1.13 on 2021-11-06 12:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='credit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Kredit narx'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Chegirma narx'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Xarakteristika'),
        ),
    ]
