# Generated by Django 3.1.13 on 2021-11-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Brend nomi')),
                ('icon', models.ImageField(blank=True, upload_to='brendlar/', verbose_name='Brend ikonkasi')),
            ],
            options={
                'verbose_name': 'brend',
                'verbose_name_plural': 'Brendlar',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='products.brand', verbose_name='Brend'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='Brend'),
        ),
    ]
