# Generated by Django 3.1.13 on 2021-11-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211113_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=10, max_length=10, verbose_name='Tartib raqami'),
        ),
    ]
