# Generated by Django 3.1.13 on 2021-11-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=10, verbose_name='Tartib raqami'),
        ),
    ]
