# Generated by Django 3.1.13 on 2021-11-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211113_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'narx', 'verbose_name_plural': 'Narxlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
    ]
