# Generated by Django 3.1.13 on 2021-11-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211120_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='credit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kredit narx'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Chegirma narx'),
        ),
    ]
