# Generated by Django 3.1.13 on 2021-11-25 20:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211120_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chegirma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzusi')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Tavsifi')),
                ('hd_photo', models.ImageField(upload_to='chegirmalar', verbose_name='Banner rasmi')),
                ('icon_photo', models.ImageField(upload_to='chegirmalar', verbose_name='Ikonka rasmi')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='products.category', verbose_name='kategoriya')),
            ],
            options={
                'verbose_name': 'chegirma',
                'verbose_name_plural': 'Chegirmalar',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='chegirma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.chegirma', verbose_name='chegirma'),
        ),
    ]
