# Generated by Django 3.1.13 on 2021-11-25 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211126_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chegirma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.chegirma', verbose_name='chegirma'),
        ),
    ]
