# Generated by Django 3.1.13 on 2021-11-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20211126_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='Chegirma'),
        ),
        migrations.AddField(
            model_name='product',
            name='lising',
            field=models.BooleanField(default=False, verbose_name='Lising'),
        ),
    ]
