# Generated by Django 3.1.13 on 2021-12-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20211128_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created',), 'verbose_name': 'mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
    ]
