# Generated by Django 3.1.13 on 2022-01-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20211212_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chegirma narx Sumda'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Narx Sumda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Chegirma narx Dollarda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Narx Dollarda'),
        ),
    ]
