# Generated by Django 3.1.13 on 2022-01-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20220106_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='credit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Kredit narx'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Chegirma narx Dollarda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Chegirma narx Sumda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, verbose_name='Narx Dollarda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Narx Sumda'),
        ),
    ]
