# Generated by Django 3.1.13 on 2022-01-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20220107_0959'),
        ('products', '0014_auto_20220107_2259'),
    ]

    operations = [
    ]
