# Generated by Django 3.1.13 on 2022-01-12 17:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20220107_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='chegirma',
            name='description_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='chegirma',
            name='description_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='chegirma',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Mavzusi'),
        ),
        migrations.AddField(
            model_name='chegirma',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Mavzusi'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tafsif'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tafsif'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Xarakteristika'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Xarakteristika'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
    ]
