# Generated by Django 3.1.13 on 2022-01-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220112_2219'),
        ('products', '0015_merge_20220108_1042'),
    ]

    operations = [
    ]
