# Generated by Django 3.1.13 on 2022-01-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220112_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Yashirish'),
        ),
    ]
