# Generated by Django 3.1.13 on 2022-01-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_category_hide'),
        ('products', '0016_merge_20220112_2301'),
    ]

    operations = [
    ]
