# Generated by Django 3.1.13 on 2022-01-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_merge_20220114_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kategoriyalar', to='products.brand', verbose_name='Brend'),
        ),
    ]
