# Generated by Django 3.1.13 on 2022-01-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_merge_20220114_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Narx Dollarda'),
        ),
    ]
