# Generated by Django 3.1.13 on 2022-01-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20220122_1912'),
        ('products', '0018_auto_20220122_1911'),
    ]

    operations = [
    ]
