# Generated by Django 3.1.13 on 2022-02-04 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_merge_20220122_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='products.brand', verbose_name='Brend'),
        ),
    ]
